import { Roboto } from 'next/font/google'
import "./globals.css";
import NavBar from '@/components/shared/NavBar';

const roboto = Roboto({
  weight: '500',
  subsets: ['latin'],
  display: 'swap',
})

export const metadata = {
  title: "My second Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme='light' >
      <body className={roboto.className}>
        <NavBar />
        {children}
      </body>
    </html>
  );
}
